GoogleCloudPlatform/functions-framework-dotnet

- Google.Cloud.Functions.Invoker/EntryPoint.cs
- Google.Cloud.Functions.Invoker/FunctionEnvironment.cs
- Google.Cloud.Functions.Invoker/Logging/FactoryLoggerProvider.cs
- Google.Cloud.Functions.Invoker/Logging/JsonConsoleLogger.cs
- Google.Cloud.Functions.Invoker/Logging/LoggerBase.cs
- Google.Cloud.Functions.Invoker/Logging/SimpleConsoleLogger.cs
- Remove the warning about overwriting a default value
- Use a one-line-per-message console writer, either simply text, or
JSON if we detect we're on k-native via the K_SERVICE environment
variable
Admittedly this loses the "prettiness" of coloured output etc - but it's a lot more appropriate for microservices in general. (And the JSON output looks great in Stackdriver. Once we've got an alpha02 nuget package, I'll deploy to Cloud Run to test that. It's tricky to do before then.)
> Simplify log output

- Google.Cloud.Functions.Invoker.Tests/FunctionEnvironmentTest.cs
- Google.Cloud.Functions.Invoker/FunctionEnvironment.cs
- README.md
Fixes #20 and improves usability quite a bit :)
> If there's only one function in the calling assembly, use that by default

- Google.Cloud.Functions.Invoker/Logging/JsonConsoleLogger.cs
We could potentially use "logName" which would be picked up by
Google Cloud Logging, but we'd almost certainly want a prefix there,
which wouldn't be easy to predict. We could add that as an extra
property in the JSON later if we want to.
> Use "category" in the JSON logger instead of "log_name"

- build.sh
- docs/README.md
- docs/examples.md
- docs/testing.md
- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.IntegrationTests/SimpleHttpFunctionTest.cs
- examples/Google.Cloud.Functions.Examples.IntegrationTests/SimpleHttpFunctionTest_WithTestServerFixture.cs
- examples/Google.Cloud.Functions.Examples.IntegrationTests/SimpleHttpFunctionTest_WithTestServerInCtor.cs
- examples/Google.Cloud.Functions.Examples.IntegrationTests/SimpleHttpFunctionTest_WithTestServerInTest.cs
- examples/Google.Cloud.Functions.Examples.sln
- src/Google.Cloud.Functions.Invoker.Testing/FunctionTestServer.cs
- src/Google.Cloud.Functions.Invoker.Testing/Google.Cloud.Functions.Invoker.Testing.csproj
- src/Google.Cloud.Functions.Invoker.Testing/Preconditions.cs
- src/Google.Cloud.Functions.Invoker.Tests/EntryPointTest.cs
- src/Google.Cloud.Functions.Invoker/ConfigurationVariableProvider.cs
- src/Google.Cloud.Functions.Invoker/EntryPoint.cs
- src/Google.Cloud.Functions.Invoker/FunctionEnvironment.cs
- src/Google.Cloud.Functions.sln
This adds a new package, Google.Cloud.Functions.Invoker.Testing,
containing a test server - as well as methods in EntryPoint to just
create an IHostBuilder where that's more desirable.
The documentation here is roughly the level and style of
documentation I'm hoping to use for other features, such as
dependency injection.
> Add integration testing functionality and documentation

- docs/README.md
- docs/launch-settings.md
- src/Google.Cloud.Functions.Invoker.Tests/FunctionEnvironmentTest.cs
- src/Google.Cloud.Functions.Invoker/FunctionEnvironment.cs
It's reasonably infeasible to "just keep working" as far as I can tell. We
could potentially ignore the command line parameter, but we'd want
to work out what port VS thinks we're listening on etc. It's cleaner
just to give more information to the user.
Fixes #41
> Detect a potential problem with launching from Visual Studio, and give a nice error

- src/Google.Cloud.Functions.Invoker.Tests/EntryPointTest.cs
- src/Google.Cloud.Functions.Invoker/FunctionEnvironment.cs
Fixes #38.
(This is the expected behaviour, according to an internal spec.)
> Return a 404 for /robots.txt and /favicon.ico

- src/Google.Cloud.Functions.Framework.Tests/CloudEventAdapterTest.cs
- src/Google.Cloud.Functions.Framework.Tests/LegacyEvents/LegacyEventAdapterTest.cs
- src/Google.Cloud.Functions.Framework/CloudEventAdapter.cs
- src/Google.Cloud.Functions.Framework/LegacyEvents/LegacyEventAdapter.cs
- src/Google.Cloud.Functions.Invoker.Tests/DependencyInjectionTest.cs
- src/Google.Cloud.Functions.Invoker.Tests/FunctionEnvironmentTest.cs
- src/Google.Cloud.Functions.Invoker/FunctionEnvironment.cs
- src/Google.Cloud.Functions.Invoker/Logging/SimpleConsoleLogger.cs
Admittedly this makes everything "that bit more magic" - but in the existing code, we create some objects ourselves and ask the framework to create others.
This PR asks ASP.NET Core DI to do more of the work - we just identify which types we need.
That then allows the rest of the PR, adding more logging in adapters... without changing any invoker code.
> When in doubt, add more dependency injection

- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Function.cs
- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Startup.cs
This is partly to avoid the "type name collision with namespace
name" aspect, and partly because I think I'm landing on Function
being a conventional entry point name in the same way that Program
is for a console application.
Fixes #45.
> Rename the TimeZoneConverter function to Function

- docs/examples.md
- examples/Directory.Build.targets
- examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Google.Cloud.Functions.Examples.FSharpHttpFunction.fsproj
- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleHttpFunction/Google.Cloud.Functions.Examples.SimpleHttpFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleLegacyEventFunction/Google.Cloud.Functions.Examples.SimpleLegacyEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj
- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj
- examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbHttpFunction/Google.Cloud.Functions.Examples.VbHttpFunction.vbproj
- examples/README.md
- examples/generate.sh
- src/Google.Cloud.Functions.Invoker/EntryPoint.cs
- update-project-references.sh
By default, all examples now reference NuGet packages. But specifying "LocalFunctionsFramework" as a property (e.g. via an environment variable) removes the package references and adds project references instead, for local development.
Fixes #53.
> Allow a simple project/package reference choice for examples

- install-local-templates.sh
This avoids a lot of error-prone manual work when the templates are updated.
> Create a simple script to install the local version of the templates

- README.md
- examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Google.Cloud.Functions.Examples.FSharpHttpFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleHttpFunction/Google.Cloud.Functions.Examples.SimpleHttpFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj
- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj
- examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbHttpFunction/Google.Cloud.Functions.Examples.VbHttpFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbUntypedEventFunction/Google.Cloud.Functions.Examples.VbUntypedEventFunction.vbproj
- src/CommonProperties.xml
- src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/http-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/http-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/http-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-vb/MyFunction.vbproj
Release 1.0.0-alpha07 of the .NET Functions Framework
New features since 1.0.0-alpha06:
- Add Firebase Realtime Database event payload type
- Add mappings for remaining GCF events (but without a payload type)
> Release 1.0.0-alpha07

- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Function.cs
The old code would convert "folder/picture.jpg" to just
"picture.txt", because it removed any directories from the path.
> Use Path.ChangeExtension to convert jpg to txt files

- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/storage.json
- src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
Other events *may* need a similar treatment - we're still finalizing
the source/subject for Firebase and Firestore events.
> Update GCF event conversion for Storage source/subject

- docs/testing.md
- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.IntegrationTests/SimpleDependencyInjectionTest.cs
- src/Google.Cloud.Functions.Invoker.Testing/FunctionTestServer.cs
- src/Google.Cloud.Functions.Invoker.Testing/TestLogEntry.cs
- src/Google.Cloud.Functions.Invoker.Testing/TestLoggerProvider.cs
(The docs state some limitations at the moment, but I think it's worth including even so.)
Fixes #93.
> Add an in-memory log provider to the test server

- README.md
- docs/history.md
- examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Google.Cloud.Functions.Examples.FSharpHttpFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleHttpFunction/Google.Cloud.Functions.Examples.SimpleHttpFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj
- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj
- examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbHttpFunction/Google.Cloud.Functions.Examples.VbHttpFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbUntypedEventFunction/Google.Cloud.Functions.Examples.VbUntypedEventFunction.vbproj
- src/CommonProperties.xml
- src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/http-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/http-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/http-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-vb/MyFunction.vbproj
Changes since 1.0.0-alpha07
- Added an in-memory logger provider to the test server
- Moved the event data classes out of the Functions Framework into
`Google.Events.*`. We have a dependency on `Google.Events` but
not on any specific serialization strategy.
- Changed the shape of the PubSub CloudEvent data to match the event
on Cloud Run. (The message is wrapped in another class that will
eventually contain the subscription name.)
- Separated out the bucket name (source) and object name (subject) for
storage CloudEvents.
> Release 1.0.0-alpha08

- build-release.sh
Without this, dotnet pack complains that SourceLink may be broken due to the conformance test submodule.
I'm not entirely sure it's correct, but cloning recursively makes
the problem go away in a cheap way.
> Clone recursively when building a release

- examples/Google.Cloud.Functions.Examples.IntegrationTests/SimpleHttpFunctionTest_WithFunctionTestBase.cs
- src/Google.Cloud.Functions.Invoker.Testing/FunctionTestBase.cs
- src/Google.Cloud.Functions.Invoker.Testing/FunctionTestServer.cs
Writing the samples has proved this to be extremely convenient.
Note: I'm very much up for a debate about the methods to include around making requests. These aren't quite like the ones in the samples - in particular, I never return HttpResponseMessage, because returning that after disposing of the client could do nasty things in some cases. (That's why I have the action for validation.)
> Add a FunctionTestBase to derive from in integration tests

- docs/examples.md
- examples/README.md
- The README.md in examples links to the examples doc page
- The doc page gives generic instructions for running examples
- Each example now has a sample deployment command for GCF
(I'm reluctant to go any further than this, given that there will be
more complete samples on cloud.google.com for beta.)
Fixes #105.
> Docs: Add more documentation for running examples

- README.md
- examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.Configuration/Google.Cloud.Functions.Examples.Configuration.csproj
- examples/Google.Cloud.Functions.Examples.CustomConfiguration/Google.Cloud.Functions.Examples.CustomConfiguration.csproj
- examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Google.Cloud.Functions.Examples.FSharpHttpFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleHttpFunction/Google.Cloud.Functions.Examples.SimpleHttpFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj
- examples/Google.Cloud.Functions.Examples.TestableDependencies/Google.Cloud.Functions.Examples.TestableDependencies.csproj
- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj
- examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbHttpFunction/Google.Cloud.Functions.Examples.VbHttpFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbUntypedEventFunction/Google.Cloud.Functions.Examples.VbUntypedEventFunction.vbproj
- src/CommonProperties.xml
- src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/http-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/http-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/http-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-vb/MyFunction.vbproj
Changes since 1.0.0-alpha08:
- Updated to use Google.Events and Google.Events.Protobuf 1.0.0-alpha04
- Updated Functions Startup classes to cover more customization and provide more context
- Updated architecture for host building to be more idiomatic to ASP.NET Core
- Kestrel heartbeat warnings are now suppressed (as they're expected due to the way functions hosts run)
- Testing package now contains a FunctionTestBase class for simple integration testing
> Release .NET Functions Framework 1.0.0-alpha09

- README.md
We've removed Travis config, so it's not accurate anymore.
Preview:
---
[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2FGoogleCloudPlatform%2Ffunctions-framework-dotnet%2Fbadge&style=flat)](https://actions-badge.atrox.dev/GoogleCloudPlatform/functions-framework-dotnet/goto)
> docs: use GH actions badge, not travis

- .github/workflows/unit.yml
This CI PR slightly changes the config to not run on every push.
- Run CI whenever:
- Pushing to master
- Pull requests
(Sorry for the extra PR)
> ci: don't run when pushing to non-master branches

- README.md
- docs/history.md
- examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.Configuration/Google.Cloud.Functions.Examples.Configuration.csproj
- examples/Google.Cloud.Functions.Examples.CustomConfiguration/Google.Cloud.Functions.Examples.CustomConfiguration.csproj
- examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Google.Cloud.Functions.Examples.FSharpHttpFunction.fsproj
- examples/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj
- examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleHttpFunction/Google.Cloud.Functions.Examples.SimpleHttpFunction.csproj
- examples/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj
- examples/Google.Cloud.Functions.Examples.TestableDependencies/Google.Cloud.Functions.Examples.TestableDependencies.csproj
- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj
- examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbHttpFunction/Google.Cloud.Functions.Examples.VbHttpFunction.vbproj
- examples/Google.Cloud.Functions.Examples.VbUntypedEventFunction/Google.Cloud.Functions.Examples.VbUntypedEventFunction.vbproj
- src/CommonProperties.xml
- src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/http-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/http-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/http-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/untyped-event-function-vb/MyFunction.vbproj
Changes since 1.0.0-alpha11 are just package renaming:
- Old Google.Cloud.Functions.Invoker package is now Google.Cloud.Functions.Hosting
- Old Google.Cloud.Functions.Invoker.Testing package is now Google.Cloud.Functions.Testing
> Release .NET Functions Framework version 1.0.0-alpha12

- examples/Google.Cloud.Functions.Examples.Middleware/Google.Cloud.Functions.Examples.Middleware.csproj
The build.sh script didn't detect the problem because we always
build with LocalFunctionsFramework set to true - which makes sense
in terms of allowing us to write examples for unreleased framework
features, but hides this sort of thing. I think it's a pretty rare
problem - I don't think we need to change the build.
> Include Hosting package in Middleware example

- README.md
- Adds GCP GCF buildpacks instructions. Super useful for building a container (anywhere).
- Does not touch any existing docs around `Dockerfiles`
- Minor formatting
Tested locally.
Feel free to make any additional changes w.r.t. Buildpacks.
> docs: format and add buildpack instructions

- .gcloudignore
- docs/deployment.md
- docs/examples.md
- examples/.gcloudignore
- examples/Directory.Build.targets
- examples/Google.Cloud.Functions.Examples.MultiProjectDependency/BusinessLogic.cs
- examples/Google.Cloud.Functions.Examples.MultiProjectDependency/Google.Cloud.Functions.Examples.MultiProjectDependency.csproj
- examples/Google.Cloud.Functions.Examples.MultiProjectFunction/Function.cs
- examples/Google.Cloud.Functions.Examples.MultiProjectFunction/Google.Cloud.Functions.Examples.MultiProjectFunction.csproj
- examples/Google.Cloud.Functions.Examples.sln
Here MultiProjectFunction depends (locally) on
MultiProjectDependency, so both projects must be uploaded together,
and the correct project specified using a build-time environment
variable.
> docs: Add an example of deploying a multi-project function

- .kokoro/autorelease.sh
This validates that the committish we build genuinely points at a
tag, and passes the tag to build-release (which expects one).
(This was basically copied from https://github.com/googleapis/google-cloudevents-dotnet/pull/48, but we already had --recursive in build-release.sh in this repo.)
> Fix autorelease build to use tags

- docs/testing.md
- examples/Google.Cloud.Functions.Examples.IntegrationTests/TestableDependenciesTest.cs
- src/Google.Cloud.Functions.Hosting/FunctionsStartupAttribute.cs
- src/Google.Cloud.Functions.Testing/FunctionTestBase.cs
- src/Google.Cloud.Functions.Testing/FunctionTestServer.cs
- src/Google.Cloud.Functions.Testing/FunctionTestServerBuilder.cs
- src/Google.Cloud.Functions.Testing/FunctionTestStartupAttribute.cs
Fixes #154.
An alternative approach would be to allow the existing
FunctionsStartupAttribute to be applied to types as well as the
assembly... in which case we'd probably want to change the framework
to find startup classes associated with the function itself. That
could potentially be quite useful...
Very happy to discuss those options.
> Add a test-oriented attribute for functions startups.

- .gitignore
- examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj
- examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj
- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj
- examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj
- src/Directory.Build.props
- src/Directory.Build.targets
- src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj
- src/Google.Cloud.Functions.Framework/AssemblyInfo.cs
- src/Google.Cloud.Functions.Framework/Google.Cloud.Functions.Framework.csproj
- src/Google.Cloud.Functions.Hosting.Tests/Google.Cloud.Functions.Hosting.Tests.csproj
- src/Google.Cloud.Functions.Hosting/AssemblyInfo.cs
- src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj
- src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj
- src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj
- src/Google.Cloud.Functions.Testing/AssemblyInfo.cs
This can't be merged until https://github.com/googleapis/google-cloudevents-dotnet/pull/56 has been merged and released.
(I've tested it with a local build.)
> Sign Functions Framework assemblies

- examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Function.fs
- examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Function.fs
- examples/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction/Function.fs
Some minor changes to the three F# samples. Hopefully they're useful.
1. The previous use of `async` was semantically incorrect / different from the C# Task version. The current F# example creates the task but never "awaits" it, it just throws it away (with `ignore`) - this is the same as in C# simply not awaiting an async (whereby you get the compiler warning). `do!` is the equivalent to `await` in this context, so I've put that in here.
2. Replace use of %A (which is a kind of magic "print out this value") with either specific modifiers for longs (%i) or ToString (%O).
3. Added the "Time" item which was in the C# examples. F# is a bit (ok, a lot) more verbose here because:
a. There's no language support for mapping / binding on nullable values, so instead you use `Option.map`.
b. …
> Minor F# changes

- src/Google.Cloud.Functions.Testing/FunctionTestServer.cs
- src/Google.Cloud.Functions.Testing/FunctionTestServerBuilder.cs
Fixes #182.
It feels like this is really a bug in TestServer, but it's easy
enough to fix it in FunctionTestServer without introducing a
breaking change.
Given that TestServer.Host throws, I've made the IHost available in
FunctionTestServer too.
> Dispose of the host instead of the TestServer in FunctionTestServer

- README.md
(It's not needed now that the package has hit 1.0.0.)
> Remove version number from template installation instructions

- examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj
- examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj
- examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj
Most importantly, this updates Google.Cloud.Vision.V1 to a version which transitively depends on a much smaller version of Grpc.Core
> Update example dependencies

- examples/Google.Cloud.Functions.Examples.CustomEventDataFunction/Google.Cloud.Functions.Examples.CustomEventDataFunction.csproj
- src/Google.Cloud.Functions.Framework.Tests/CloudEventAdapterTDataTest.cs
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs
- src/Google.Cloud.Functions.Framework/CloudEventAdapterTData.cs
- src/Google.Cloud.Functions.Framework/Google.Cloud.Functions.Framework.csproj
- src/Google.Cloud.Functions.Hosting/Google.Cloud.Functions.Hosting.csproj
The code changes are to handle the nullable reference types which
are now in the SDK. The Functions Framework itself still doesn't
advertise anything around nullable reference types - that's a change
that *could* come later if we want to.
> Update CloudEvents SDK dependencies

- docs/examples.md
(Discovered while answering a Stack Overflow question...)
> docs: Add missing backslash to sample deployment command line

- README.md
Replaces README badges. GitHub Actions has native badges and badge.atrox.dev is broken.
Feel free to say the formatting should be different.
> docs: update broken badge

- docs/deployment.md
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfEventResources.cs
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/emulator_pubsub.json
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/raw_pubsub.json
- src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj
- src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
- src/Google.Cloud.Functions.Framework/GcfEvents/Request.cs
> feat: Support Pub/Sub push notifications format (adapt to CloudEvent)

- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs
- src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs
- src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj
- src/Google.Cloud.Functions.Framework/CloudEventAdapter.cs
- src/Google.Cloud.Functions.Framework/CloudEventAdapterTData.cs
- src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
Closes #239 (in conjunction with a discussion of Functions Frameworks owners)
Currently we warn on every request. Warning only once would be
feasible, but only globally, which isn't ideal.
> feat: Warn if the "unknown topic" resource name is used

- .github/workflows/buildpack-integration-test.yaml
- src/Google.Cloud.Functions.ConformanceTests/HttpFunction.cs
- src/Google.Cloud.Functions.ConformanceTests/UntypedCloudEventFunction.cs
- src/Google.Cloud.Functions.ConformanceTests/create-standalone.sh
- src/Google.Cloud.Functions.ConformanceTests/standalone-nuget.config
This will ensure that any changes to the Functions Framework are
compatible with the buildpack. In order to use the latest source
code, it builds the Functions Framework locally and includes the
package file in a temporary copy of the conformance tests, along
with a nuget.config file to use that local package.
> test: Creates a buildpack validation action

- .github/workflows/conformance.yml
- run-conformance-tests.sh
- src/Google.Cloud.Functions.ConformanceTests/ConcurrentHttpFunction.cs
Tests that the framework can handle 10 requests to a function that
sleeps for 1s in about 1s.
> chore: enable concurrency conformance tests

- .github/workflows/buildpack-integration-test.yaml
This will install the latest version, rather than using the default. We need this as we build the latest version of the Functions Framework for the integration test.
> chore: Install .NET Core in buildpack integration test

- .github/workflows/buildpack-integration-test.yaml
- global.json
We need to work out how to get the latest version of the SDK when running the buildpack integration test
> chore: Revert .NET SDK version changes

- .github/release-please.yml
- .github/release-trigger.yml
- .release-please-manifest.json
- release-please-config.json
The enables release-please while only updating the `src/CommonProperties.xml` file. Post-processing should update the remaining files.
This an example PR created from the above config: https://github.com/GoogleCloudPlatform/functions-framework-dotnet/pull/269
> build: enable release-please

- .release-please-manifest.json
- release-please-config.json
We release all of the Functions Framework together, even though it's four packages - like GAX. We don't want or need to keep track of the versions or history for the separate packages separately.
> chore: Refactor release-please to be a single component

- .github/workflows/buildpack-integration-test.yaml
Using the "dotnet" builder should work for both dotnet3 and dotnet6.
> chore: Update buildpack integration test to use latest tag implicitly

- src/CommonProperties.xml
We still include the license file within the package, so we continue to meet all obligations, but this is easier for customers to validate.
(Non-urgent to review.)
> chore: Update packaging to use PackageLicenseExpression

- src/Google.Cloud.Functions.ConformanceTests/create-standalone.sh
We need to build the code with whatever .NET SDK is installed in the buildpack. We shouldn't force that to be the same SDK that the Functions Framework itself uses for its normal build.
> tests: Fix buildpack integration tests

- .github/workflows/codeql.yml
Adding missing endpoints for push action
> chore: add missing endpoints to policy

- run-conformance-tests.sh
- src/Google.Cloud.Functions.ConformanceTests/TypedFunction.cs
Changes
* Adds new conformance test function `TypedFunction` using the typed function signature.
* Updates conformance client version to the latest release with support for typed function conformance testing.
* Updates `run-conformance-tests.sh` to include the new test.
The new test expects a function to be called with a JSON object `{"a":"b"}` and to return that payload as a `payload` field of its response i.e. `{"payload": {"a": "b"}}`.
> chore: add conformance test coverage for typed function signature

- README.md
From version 2.0.0 of the package .NET 6 became the min version: https://www.nuget.org/packages/Google.Cloud.Functions.Hosting/2.0.0#supportedframeworks-body-tab
> fix(readme): min dotnet version

- docs/deployment.md
Note that we don't have any examples targeting .NET 8, partly as we're still building on .NET 6.
Fixes #444.
> docs: Deployment instructions for .NET 8

- src/Google.Cloud.Functions.Hosting.Tests/Logging/JsonConsoleLoggerTest.cs
- src/Google.Cloud.Functions.Hosting.Tests/Logging/LoggingIntegrationTest.cs
- src/Google.Cloud.Functions.Hosting.Tests/Logging/SimpleConsoleLoggerTest.cs
- src/Google.Cloud.Functions.Hosting/Extensions/FunctionsFrameworkLoggingExtensions.cs
- src/Google.Cloud.Functions.Hosting/Logging/FactoryLoggerProvider.cs
- src/Google.Cloud.Functions.Hosting/Logging/JsonConsoleLogger.cs
- src/Google.Cloud.Functions.Hosting/Logging/LoggerBase.cs
- src/Google.Cloud.Functions.Hosting/Logging/SimpleConsoleLogger.cs
- src/Google.Cloud.Functions.Testing/MemoryLogger.cs
- src/Google.Cloud.Functions.Testing/MemoryLoggerProvider.cs
Our logging providers need to implement ISupportExternalScope in order to retain scopes from Kestrel.
Fixes #509.
> fix: Propagate framework scopes

- .config/dotnet-tools.json
- .kokoro/autorelease.sh
Release 2.2.1 contains the same code as 2.2.0, but the 2.2.0 release failed after only releasing some of the packages. The 2.2.1 release should be complete with all packages.
This commit updates the SBOM generator to the latest version, and changes the build script to avoid similar partial failures in the future.
Release-As: 2.2.1
> chore: Update SBOM generator

- src/Google.Cloud.Functions.Testing/Google.Cloud.Functions.Testing.csproj
So that we can close #524 which is currently an inmortal PR.
> chore: Update Microsoft.AspNetCore.TestHost dependency

- .github/workflows/codeql.yml
Previously we were just using whatever version was present, which included .NET 6 - but not that .NET 6 is deprecated, we need to install it explicitly.
(We'll change all of this when we retarget to .NET 8, which should be soon.)
Fixes b/388692803
> chore: Explicitly install .NET 6 for the CodeQL test
