GoogleCloudPlatform/functions-framework-dotnet

README.md
(This was intended to be in #4, but the push failed due to dodgy mobile wifi without me noticing.)
=> Add Travis build status to README (and fix rogue Java reference)

.travis.yml, FunctionsFramework.sln, Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, Google.Cloud.Functions.Framework.Tests/UnitTest1.cs, Google.Cloud.Functions.Framework/AssemblyInfo.cs, Google.Cloud.Functions.Invoker.Tests/Google.Cloud.Functions.Invoker.Tests.csproj, Google.Cloud.Functions.Invoker.Tests/UnitTest1.cs, Google.Cloud.Functions.Invoker/AssemblyInfo.cs, global.json
No useful tests in this commit.
=> Skeleton for test projects

Google.Cloud.Functions.SampleHttpFunction/Google.Cloud.Functions.SampleHttpFunction.csproj, Google.Cloud.Functions.SampleHttpFunction/generate.sh
(We know we don't want to package this porject.)
=> Disable a "non-packable project" warning

Google.Cloud.Functions.Invoker.Tests/FunctionEnvironmentTest.cs, Google.Cloud.Functions.Invoker/FunctionEnvironment.cs
=> Use DOTNET_RUNNING_IN_CONTAINER to determine which IP address to listen on

build.sh, src/CommonProperties.xml, src/Google.Cloud.Functions.Framework/Google.Cloud.Functions.Framework.csproj, src/Google.Cloud.Functions.Invoker.Testing/Google.Cloud.Functions.Invoker.Testing.csproj, src/Google.Cloud.Functions.Invoker/Google.Cloud.Functions.Invoker.csproj, src/Google.Cloud.Functions.Templates/Google.Cloud.Functions.Templates.csproj
=> Minor build simplifications

docs/README.md, docs/dependency-injection.md, docs/examples.md, examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Function.cs, examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj, examples/Google.Cloud.Functions.Examples.IntegrationTests/AdvancedDependencyInjectionTest.cs, examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj, examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Function.cs, examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj, examples/Google.Cloud.Functions.Examples.sln
(Additionally, test the "advanced" dependency injection example.)
=> Add examples of dependency injection, along with documentation

docs/examples.md, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/ConversionResult.cs, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/ConversionType.cs, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/README.md, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Startup.cs, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/TimeZoneConverter.cs, examples/Google.Cloud.Functions.Examples.sln
This is intended to show something more than "hello world", partly
to get the feeling of what real function development is like.
=> Add a more "business useful" example function

README.md, src/CommonProperties.xml, src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj, src/Google.Cloud.Functions.Templates/templates/http-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/http-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/http-function-vb/MyFunction.vbproj, update-template-references.sh
=> Release 1.0.0-alpha03

docs/examples.md, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Function.cs, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/README.md, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Startup.cs, examples/Google.Cloud.Functions.Examples.sln
(I'm never quite sure how many comments to add for this sort of sample. Let me know if you think we need more or fewer.)
=> Add example of a legacy event function

examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Function.fs, examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Function.cs, examples/Google.Cloud.Functions.Examples.SimpleLegacyEventFunction/Function.cs, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Function.cs, examples/Google.Cloud.Functions.Examples.VbEventFunction/CloudFunction.vb, src/Google.Cloud.Functions.Framework.Tests/CloudEventAdapterTest.cs, src/Google.Cloud.Functions.Framework.Tests/LegacyEvents/LegacyEventAdapterTest.cs, src/Google.Cloud.Functions.Framework/CloudEventAdapter.cs, src/Google.Cloud.Functions.Framework/ICloudEventFunction.cs, src/Google.Cloud.Functions.Framework/LegacyEvents/ILegacyEventFunction.cs, src/Google.Cloud.Functions.Framework/LegacyEvents/LegacyEventAdapter.cs, src/Google.Cloud.Functions.Invoker.Tests/FunctionEnvironmentTest.cs, src/Google.Cloud.Functions.Templates/templates/event-function-cs/Function.cs, src/Google.Cloud.Functions.Templates/templates/event-function-fs/Function.fs, src/Google.Cloud.Functions.Templates/templates/event-function-vb/CloudFunction.vb, src/Google.Cloud.Functions.Templates/templates/legacy-event-function-cs/Function.cs
Fixes #50.
(I'm happy to consider alternative options if you can think of them.)
=> Provide a cancellation token for event functions

examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj, examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj, examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Google.Cloud.Functions.Examples.FSharpHttpFunction.fsproj, examples/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction.fsproj, examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj, examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj, examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj, examples/Google.Cloud.Functions.Examples.SimpleHttpFunction/Google.Cloud.Functions.Examples.SimpleHttpFunction.csproj, examples/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction.csproj, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj, examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj, examples/Google.Cloud.Functions.Examples.VbHttpFunction/Google.Cloud.Functions.Examples.VbHttpFunction.vbproj, examples/Google.Cloud.Functions.Examples.VbUntypedEventFunction/Google.Cloud.Functions.Examples.VbUntypedEventFunction.vbproj, src/CommonProperties.xml, src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj, src/Google.Cloud.Functions.Templates/templates/http-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/http-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/http-function-vb/MyFunction.vbproj, src/Google.Cloud.Functions.Templates/templates/untyped-event-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/untyped-event-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/untyped-event-function-vb/MyFunction.vbproj
New features since 1.0.0-alpha04:
- Update the events programming model:
- All events are Cloud Events; GCF-events are now synthesized into
CloudEvents
- Event functions are typed (in which case the data is deserialized
automatically) or untyped (in which case only the event is
provided)
- Templates available across all languages
=> Release 1.0.0-alpha05 of the .NET Functions Framework

src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/legacy_pubsub.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/legacy_storage_change.json, src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
=> Handle legacy storage and PubSub events in GcfConverters

README.md, examples/Google.Cloud.Functions.Examples.AdvancedDependencyInjection/Google.Cloud.Functions.Examples.AdvancedDependencyInjection.csproj, examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj, examples/Google.Cloud.Functions.Examples.FSharpHttpFunction/Google.Cloud.Functions.Examples.FSharpHttpFunction.fsproj, examples/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction/Google.Cloud.Functions.Examples.FSharpUntypedEventFunction.fsproj, examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj, examples/Google.Cloud.Functions.Examples.SimpleDependencyInjection/Google.Cloud.Functions.Examples.SimpleDependencyInjection.csproj, examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj, examples/Google.Cloud.Functions.Examples.SimpleHttpFunction/Google.Cloud.Functions.Examples.SimpleHttpFunction.csproj, examples/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction/Google.Cloud.Functions.Examples.SimpleUntypedEventFunction.csproj, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj, examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj, examples/Google.Cloud.Functions.Examples.VbHttpFunction/Google.Cloud.Functions.Examples.VbHttpFunction.vbproj, examples/Google.Cloud.Functions.Examples.VbUntypedEventFunction/Google.Cloud.Functions.Examples.VbUntypedEventFunction.vbproj, src/CommonProperties.xml, src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj, src/Google.Cloud.Functions.Templates/templates/http-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/http-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/http-function-vb/MyFunction.vbproj, src/Google.Cloud.Functions.Templates/templates/untyped-event-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/untyped-event-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/untyped-event-function-vb/MyFunction.vbproj
New features since 1.0.0-alpha05:
- Convert legacy Storage and PubSub events to Cloud Events
=> Release 1.0.0-alpha06 of the .NET Functions Framework

src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db1.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db2.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db3.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db4.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db5.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db6.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db7.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-db8.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-dbdelete1.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-dbdelete2.json, src/Google.Cloud.Functions.Framework/GcfEvents/FirebaseDatabaseEvent.cs, src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
This is described at https://cloud.google.com/functions/docs/calling/realtime-database
(There are more sample JSON files than I'd normally include, but as the data isn't clearly typed, I thought it would be best to specify it like this.)
=> Add Firebase Realtime Database event support

run-conformance-tests.sh
This allows us to use "cloudevent" as the name
=> Update conformance test submodule

src/Google.Cloud.Functions.Invoker/Logging/JsonConsoleLogger.cs, src/Google.Cloud.Functions.Invoker/Logging/LoggerBase.cs, src/Google.Cloud.Functions.Invoker/Logging/SimpleConsoleLogger.cs
(First commit is just refactoring; second commit is just about heartbeats.)
=> Fix heartbeat warning

docs/customization.md
(Spotted by eagle-eyed reviewer...)
=> Fix typo in customization docs

examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Function.fs, examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj, examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Function.cs, examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj, examples/Google.Cloud.Functions.Examples.VbEventFunction/CloudFunction.vb, examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj, src/Google.Cloud.Functions.Framework.Tests/CloudEventAdapterTDataTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs, src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, src/Google.Cloud.Functions.Framework.Tests/TestResourceHelper.cs, src/Google.Cloud.Functions.Framework/Google.Cloud.Functions.Framework.csproj, src/Google.Cloud.Functions.Invoker.Tests/FunctionTargetTest.cs, src/Google.Cloud.Functions.Invoker.Tests/Google.Cloud.Functions.Invoker.Tests.csproj, src/Google.Cloud.Functions.Templates/templates/event-function-cs/Function.cs, src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/event-function-fs/Function.fs, src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/event-function-vb/CloudFunction.vb, src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj
=> Update events packages

src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs, src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
=> Format Firestore subject/source as we expect for native CloudEvents

src/Google.Cloud.Functions.Invoker.Testing/FunctionTestBase.cs
(The need for this was discovered when writing tests against more event-based functions...)
=> Add more convenience methods for testing

.github/workflows/conformance.yml, .github/workflows/unit.yml, run-conformance-tests.sh
=> Conformance test fixes and CI workflow

.kokoro/autorelease.bat, .kokoro/autorelease.sh, .kokoro/populatesecrets.sh
Once a successful release has been created using this tooling, I'll write documentation.
=> Create release scripts for use with internal Kokoro

RELEASING.md, create-release-commit.sh
(Not sure how much of the automation actually happens yet, but we can edit that after trying...)
=> Add release instructions and a helpful script

src/Google.Cloud.Functions.Testing.Tests/FunctionTestBaseTest.cs, src/Google.Cloud.Functions.Testing.Tests/Google.Cloud.Functions.Testing.Tests.csproj, src/Google.Cloud.Functions.Testing/TestLogEntry.cs, src/Google.Cloud.Functions.sln
~~First commits are from #168~~ (now rebased)
=> Improve TestLogEntry (and make test projects consistent)

src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-remote-config.json, src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
There's a little more left to do here, but this sorts out *most* of the source/subject changes.
(All of this is still a little tentative, but feels likely to be right.)
=> Improve Firebase/Firestore event conversions

src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-analytics-no-app-id.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-analytics-no-event-name.json, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/firebase-analytics.json, src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
(This should be the last event type we need to support, as far as I'm aware.)
=> Add Firebase Analytics custom conversion and sample data

.github/workflows/conformance.yml, .github/workflows/unit.yml
Fixes flakiness in Windows build
See https://github.com/actions/setup-dotnet/issues/155
=> Clear NuGet cache before building

src/Google.Cloud.Functions.Hosting.Tests/Logging/JsonConsoleLoggerTest.cs, src/Google.Cloud.Functions.Hosting.Tests/Logging/SimpleConsoleLoggerTest.cs, src/Google.Cloud.Functions.Hosting/Extensions/FunctionsFrameworkLoggingExtensions.cs, src/Google.Cloud.Functions.Hosting/Logging/JsonConsoleLogger.cs, src/Google.Cloud.Functions.Hosting/Logging/LoggerBase.cs, src/Google.Cloud.Functions.Hosting/Logging/SimpleConsoleLogger.cs
=> Record scopes in the simple and JSON loggers

src/Google.Cloud.Functions.Framework.Tests/GcfEvents/EventDeserializationTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/pubsub_text_microsecond_precision.json, src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, src/Google.Cloud.Functions.Framework/GcfEvents/GcfConverters.cs
I expect the conformance tests may fail now - they'll be updated at least for the PubSub data. (The topic and bucket parts may come a bit later.)
=> Implement extension attributes and additional PubSub data population

examples/Google.Cloud.Functions.Examples.CustomEventDataFunction/Google.Cloud.Functions.Examples.CustomEventDataFunction.csproj, src/Google.Cloud.Functions.Framework/Google.Cloud.Functions.Framework.csproj, src/Google.Cloud.Functions.Hosting/Google.Cloud.Functions.Hosting.csproj
(The only difference is how the Nullable dependency is packaged.)
=> chore: Update CloudEvents dependencies to 2.1.1

examples/Google.Cloud.Functions.Examples.CustomEventDataFunction/Google.Cloud.Functions.Examples.CustomEventDataFunction.csproj, examples/Google.Cloud.Functions.Examples.FSharpEventFunction/Google.Cloud.Functions.Examples.FSharpEventFunction.fsproj, examples/Google.Cloud.Functions.Examples.SimpleEventFunction/Google.Cloud.Functions.Examples.SimpleEventFunction.csproj, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj, examples/Google.Cloud.Functions.Examples.VbEventFunction/Google.Cloud.Functions.Examples.VbEventFunction.vbproj, src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, src/Google.Cloud.Functions.Framework/Google.Cloud.Functions.Framework.csproj, src/Google.Cloud.Functions.Hosting.Tests/Google.Cloud.Functions.Hosting.Tests.csproj, src/Google.Cloud.Functions.Hosting/Google.Cloud.Functions.Hosting.csproj, src/Google.Cloud.Functions.Templates/templates/event-function-cs/MyFunction.csproj, src/Google.Cloud.Functions.Templates/templates/event-function-fs/MyFunction.fsproj, src/Google.Cloud.Functions.Templates/templates/event-function-vb/MyFunction.vbproj, src/Google.Cloud.Functions.Testing.Tests/Google.Cloud.Functions.Testing.Tests.csproj
This updates the dependencies on both Google.Events.Protobuf and the CloudNative.CloudEvents packages
=> chore: Update dependencies

.github/.OwlBot.lock.yaml, .github/.OwlBot.yaml, owl-bot-post-processor/main.sh
This will allow us to have a very simple release-please configuration to change a single file, and drive all other files off that.
=> chore: Add OwlBot to this repo

.github/workflows/codeql.yml
Configure https://codeql.github.com/ vulnerability scanning workflow
=> feat: configure codeql security scanning

examples/Google.Cloud.Functions.Examples.CustomConfiguration/Google.Cloud.Functions.Examples.CustomConfiguration.csproj, examples/Google.Cloud.Functions.Examples.CustomEventDataFunction/Google.Cloud.Functions.Examples.CustomEventDataFunction.csproj, examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj, examples/Google.Cloud.Functions.Examples.StorageImageAnnotator/Google.Cloud.Functions.Examples.StorageImageAnnotator.csproj, examples/Google.Cloud.Functions.Examples.TimeZoneConverter/Google.Cloud.Functions.Examples.TimeZoneConverter.csproj, src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, src/Google.Cloud.Functions.Framework/Google.Cloud.Functions.Framework.csproj, src/Google.Cloud.Functions.Hosting.Tests/Google.Cloud.Functions.Hosting.Tests.csproj, src/Google.Cloud.Functions.Testing.Tests/Google.Cloud.Functions.Testing.Tests.csproj, src/Google.Cloud.Functions.Testing/Google.Cloud.Functions.Testing.csproj
=> chore: Update dependencies for 2.0.0 release

.kokoro/pip-requirements.txt, .kokoro/requirements.txt
These are now the same as for google-cloud-dotnet, for simplicity of updating.
=> chore: Update pip requirements files

src/Google.Cloud.Functions.Framework.Tests/TypedFunctionAdapterTest.cs, src/Google.Cloud.Functions.Framework/IHttpRequestReader.cs, src/Google.Cloud.Functions.Framework/IHttpResponseWriter.cs, src/Google.Cloud.Functions.Framework/ITypedFunction.cs, src/Google.Cloud.Functions.Framework/TypedFunctionAdapter.cs, src/Google.Cloud.Functions.Hosting.Tests/FunctionTargetTest.cs, src/Google.Cloud.Functions.Hosting.Tests/TypedFunctionTest.cs, src/Google.Cloud.Functions.Hosting/HostingInternals.cs
Implements a strongly typed function signature that provides automatic request deserialization and response serialization for dotnet.
=> feat: Implement strongly typed function signatures for dotnet

examples/Google.Cloud.Functions.Examples.IntegrationTests/Google.Cloud.Functions.Examples.IntegrationTests.csproj, src/Google.Cloud.Functions.Framework.Tests/GcfEvents/GcfConvertersTest.cs, src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, src/Google.Cloud.Functions.Hosting.Tests/Google.Cloud.Functions.Hosting.Tests.csproj, src/Google.Cloud.Functions.Testing.Tests/Google.Cloud.Functions.Testing.Tests.csproj
The analyzer found a tiny bug in a test, so we couldn't just use the Renovate PR.
=> chore: Update xunit and xunit runner

docs/deployment.md, docs/examples.md
This was from feedback in https://stackoverflow.com/questions/78293590
=> docs: Clarify GOOGLE_BUILDABLE meaning

.github/workflows/scorecard.yml
(It accesses www.bestpractices.dev)
=> chore: Fix the OSS Scorecard action

.github/workflows/scorecard.yml
(If this doesn't work, I may well just remove it...)
=> chore: Another attempt to fix the scorecard action

src/Google.Cloud.Functions.Testing/Google.Cloud.Functions.Testing.csproj
=> chore(deps): Update Microsoft.AspNetCore.TestHost

src/Google.Cloud.Functions.Framework.Tests/Google.Cloud.Functions.Framework.Tests.csproj, src/Google.Cloud.Functions.Hosting.Tests/Google.Cloud.Functions.Hosting.Tests.csproj, src/Google.Cloud.Functions.Testing.Tests/Google.Cloud.Functions.Testing.Tests.csproj
- xunit: 2.9.2 => 2.9.3
- xunit.runner.visualstudio: 3.0.0 => 3.0.1
=> chore(deps): update xunit-dotnet monorepo

.github/workflows/codeql.yml, .github/workflows/conformance.yml, .github/workflows/lint.yml, .github/workflows/unit.yml
This is #617 rebased and with codeql added to it.
=> chore(deps): update actions/setup-dotnet action to v4.2.0

.github/workflows/codeql.yml, .github/workflows/conformance.yml, .github/workflows/lint.yml, .github/workflows/scorecard.yml, .github/workflows/unit.yml
Added to all workflows, even though only conformance is *currently* failing.
=> chore: Add Symantec cert validation to allowed outbound hosts

README.md
=> docs: Refer to Cloud Run Functions in the README
